[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyrestsdk"
authors = [{name = "michaeldcanady"}]
readme = "Readme.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies = [
    "black==22.12.0",
    "certifi==2022.12.7",
    "cffi==1.15.1",
    "charset-normalizer==2.1.1",
    "click==8.1.3",
    "colorama==0.4.6",
    "cryptography==38.0.4",
    "idna==3.4",
    "mypy-extensions==0.4.3",
    "pathspec==0.10.3",
    "platformdirs==2.6.0",
    "pycparser==2.21",
    "pyspnego==0.7.0",
    "requests==2.28.1",
    "requests-kerberos==0.14.0",
    "tomli==2.0.1",
    "urllib3==1.26.13",
    "typing_extensions==4.4.0",
]

[project.urls]
homepage = "https://github.com/michaeldcanady/pyrestsdk#readme"
repository = "https://github.com/michaeldcanady/pyrestsdk"

[tool.flit.module]
name = "pyrestsdk"

[tool.mypy]
warn_unused_configs = true
files = "pyrestsdk"
ignore_missing_imports = true

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
column_limit = 100

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]