name: Publish pyservicenow package to PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Create release and publish distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          sudo apt install heimdal-dev
          poetry install

      - name: Publish the distibution to PyPI
        if: github.repository == 'michaeldcanady/pyrestsdk'
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
