name: Lint package with Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-major-version: [3]
        python-minor-version: [8, 9, 10, 11]
        poetry-version: ['1.4.1']
    env:
        python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version) }}

    name: Python ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version) }} - Poetry ${{poetry-version}}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.python-version }}

    - name: Install Poetry ${{ matrix.poetry-version }}
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: |
        sudo apt install heimdal-dev
        poetry install --no-interaction --no-root --with lint

    - name: Analysing the code with pylint
      if: ${{ matrix.python-minor-version >= 10 }}
      run: poetry run pylint $(git ls-files '*.py')
    
    - name: Analysing the code with pylint
      if: ${{ matrix.python-minor-version < 10 }}
      run: poetry run pylint $(git ls-files '*.py') --ignore _base_request310.py
