name: Test package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        poetry-version: ["1.4.1"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: |
        sudo apt install heimdal-dev
        poetry install --no-interaction --no-root --with test

    - name: Test with pytest
      run: poetry run pytest
      env:
        USERNAME: '${{secrets.USERNAME}}'
        PASSWORD: '${{secrets.PASSWORD}}'
        INSTANCE: '${{secrets.INSTANCE}}'
